config/routes.rb
IVote::Application.routes.draw do
  resources :votes

  resources :settings
  
  devise_for :proxies

  get "users/index"

  get "voting/index"

  post "voting/vote"

  get "voting/confirm"
  
  match "voting/quickpick" => 'voting#quickpick'
  
  post "voting/quickvote"

  resources :candidates

  devise_for :users

  get "public/index"
  
  match 'admin/tally' => 'admin#tally'
  
  get 'admin/advance'
  
  get 'admin/wipe'
  
  get 'elections/election'
  
  post 'elections/vote'
  
  root :to => 'public#index'
  
  get 'admin/irv_tally'
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
  match 'users/assign_proxy' => 'users#assign_proxy'
  
  post 'users/proxy_assign'

  post 'users/:id/admin', to: 'users#admin'
  post 'users/:id/unadmin', to: 'users#unadmin'

  resources :users
  
  resources :proxies

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "vOTe" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <![endif]-->

      <%= stylesheet_link_tag "application", :media => "all" %>



    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
 
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">vOTe</a>
        <div class="nav-collapse">
          <ul class="nav">
           <% if current_proxy %>
              <li><%= link_to "Voting", "/voting/index"  %></li>
                <% if current_proxy.email == "admin@gmail.com"%>
                  <li><%= link_to "Edit Candidates", "/candidates"  %></li>
                  <li><%= link_to "Tally", "/admin/tally"  %></li> 
                  <li><%= link_to "Users", "/users/index"  %></li>
                  <% end %>          
        
           <%end%>
           <!-- currently signed in -->
           <% if current_proxy %>
           <li><%= link_to "Sign out", destroy_user_session_path,:method => :delete, id: "sign_out" %></li>
          <!-- need to sign in -->
          <% else %>
             <li> <%= link_to "Sign In With Email", new_proxy_session_path, id: "sign_in"%>
          <% end %>




             </ul>
           </div><!--/.nav-collapse -->
         </div>
       </div>
     </div>
     <div class="container">


      <%= yield %>





      <footer style>
        <p>&copy; Scottie Biddle, Allison Pearce, Lily Wang, and Sean Reidy on behalf of Tau Gamma Chapter of Theta Tau Professional Engineering Fraternity 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
  </html>